name: 'Firefox Addon Action'

on:
  # push:
  #   branches: [ master ]
  #borrar despues el pr
  pull_request: 
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Main
          run: |
            ls
      - uses: trmcnvn/firefox-addon@v1
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: '{785fbcae-38fc-4bd2-9813-50bcad4ac35a}'
          xpi: instextension.xpi # build/my-addon.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

