name: 'Firefox Addon Action'

on:
  # push:
  #   branches: [ master ]
  #borrar despues el pr
  pull_request: 
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3.5.0
      - name: Main
        run: 
          ls /home/runner/work/instextension/instextension
      - uses: trmcnvn/firefox-addon@v1
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: '{feb6c5e7-41e5-4da1-a08f-5e3b73055be2}'
          xpi: instextension.xpi # build/my-addon.xpi
          manifest: src/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

